project:
  type: website
  render:
    - "*.qmd"
    - "!workshops/*.qmd"   # do not render this file
  resources:
    - docs/**
    - workshops/r_quartofile.qmd      # copy it to the site if you want it downloadable
    - workshops/*.pdf
  output-dir: docs

website:
  title: "ASA DataFest @ Cal Poly - SLO"
  announcement:
    icon: info-circle
    dismissable: false
    content: "Help us fund next year's event; visit <https://crowdfund.calpoly.edu/project/49615> by May 9th!"
    type: primary
    position: below-navbar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: faq.qmd
        text: FAQ
      - href: prep.qmd
        text: Preparation
      - href: judges.qmd
        text: Mentors/Judges
      - href: past-events.qmd
        text: Past Events
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


